minio:
  accessKey: minio
  secretKey: minio123
  bucket: testminio
  endpoint: http://192.168.170.1:9000
  readPath: http://192.168.170.1:9000

  servlet:
    multipart:
      # 单个上传文件的最大值是200mb
      max-file-size: 200MB
      # 单次请求的最大值
      max-request-size: 200MB
